prep:
  seed: 0
aug:
  x_shift: 0.025
  y_shift: 0.025
  rot: 15
  zoom_min: 0.9
  zoom_max: 1.2
  seed: 0
train:
  lr: 0.003
  bs: 128
  epochs: 10
  selector: random
  init_size: 1000
  stages:
    - size: 1000
      count: 9
    - size: 2000
      count: 10
    - size: 10000
      count: 4