prep:
  seed: 4
aug:
  x_shift: 0.025
  y_shift: 0.025
  rot: 15
  zoom_min: 0.9
  zoom_max: 1.2
  seed: 0
train:
  lr: 0.003
  bs: 128
  epochs: 30
  selector: sm
  init_size: 2000
  stages:
  - size: 2000
    count: 5
  - size: 5000
    count: 4
  - size: 10000
    count: 1
