prep:
  train_size: 1000
  seed: 0
aug:
  x_shift: 0.025
  y_shift: 0.025
  rot: 15
  zoom_min: 0.9
  zoom_max: 1.2
  seed: 0
train:
  lr: 0.003
  bs: 128
  epochs: 30
  stages:
    # 250-2000
    - size: 100
      count: 9 # first round initializes with stage size
    # 1500-10000
    - size: 500
      count: 16
    # 11000 - 30000
    # - size: 1000
    #   count: 20