aug:
  x_shift: 0.025
  y_shift: 0.025
  rot: 15
  zoom_min: 0.9
  zoom_max: 1.2
  seed: 0
train:
  dataset: fashion_mnist
  seed: 1
  lr: 0.003
  bs: 128
  epochs: 30
  selector: lc
  init_size: 500
  run_full: true
  stages:
  - size: 500
    count: 4
  - size: 1000
    count: 2
  - size: 2000
    count: 3
  - size: 5000
    count: 4
  - size: 10000
    count: 2
